apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: awhic-poi-map-app-dev
  annotations:
    argocd/app-name: awhic-poi-map-app-dev
    backstage.io/kubernetes-id: awhic-poi-map-app
    backstage.io/kubernetes-namespace: awhic
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-deploy/awhic-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/dev-pipelines/ns/awhic/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.a1jxqhzp.eastus2.aroapp.io/k8s/ns/awhic/deployments/awhic-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.a1jxqhzp.eastus2.aroapp.io/#https://github.com/rhdh-deploy/awhic-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://awhic-poi-map-app-awhic.apps.a1jxqhzp.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/awhic"
  system: workshop-system-awhic
  consumesApis:
    - gateway-api-awhic
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-awhic
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/awhic"
